name: 'Go Semver Release'
description: 'Computes the next, if any, semver for a local or remote Git repository and add it as an annotated tag'
branding:
  icon: 'at-sign'
  color: 'green'
inputs:
  repository-path:
    description: 'Path to the local Git repository'
    required: true
    default: ''
  tag-prefix:
    description: 'A prefix to append to the semantic version number used to name tag (e.g. "v") and used to match existing tags on remote'
    required: false
    default: ''
  branch:
    description: 'The branch on which the fetch the commits used to compute the semantic version'
    required: false
    default: ''
  dry-run:
    description: 'Enable dry-run which prevents pushing any tag, only computes the next - if any - semantic version'
    required: false
    default: 'false'
  verbose:
    description: 'Enable verbose output showing which commit triggered a release (if any) and its type'
    required: false
    default: 'false'
outputs:
  SEMVER:
    description: 'The newly computed version or the current one if no new version were computed'
  NEW_RELEASE:
    description: 'Boolean that indicate whether a new semver was computed or not'
runs:
  using: 'docker'
  image: 'build/Dockerfile'
  args:
    - "--help"